# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ACTLOG' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  # Pods for ACTLOG

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  target 'ACTLOGTests' do
    inherit! :search_paths
    # Pods for testing
  end
end